apiVersion: v1
kind: Service
metadata:
  name: openvpn-exporter
  namespace: default
  labels:
    app: openvpn-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: openvpn-exporter
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
